services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      - next-app-data:/app/data
    networks:
      - caddy_network

volumes:
  next-app-data:
    driver: local

networks:
  caddy_network:
    external: true
