import type { Metadata } from "next";
<<<<<<< HEAD

import "./globals.css";


=======

import { Providers } from "@/components/UiProviders";

import "./globals.css";

>>>>>>> 95c5c253fa2db8355e6bfd6bd86f6e6284b8359f
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
<<<<<<< HEAD
        {children}
=======
        <Providers>
          {children}
        </Providers>
>>>>>>> 95c5c253fa2db8355e6bfd6bd86f6e6284b8359f
      </body>
    </html>
  );
}
